# PyTorch Medical AI — Real PneumoniaMNIST Chest X-Ray Classification

**Real-data computer-vision portfolio project**

[Open this notebook in Google Colab](https://colab.research.google.com/github/Jorgoluka100/uni_projects/blob/main/PyTorch_medical_AI_xray_diagnosis.ipynb)

> **Dataset policy:** this notebook uses **real pediatric chest X-ray images** from the official MedMNIST distribution. Synthetic images are not used for training, validation, or headline test metrics.

> **Clinical safety note:** MedMNIST is intended for research and education, not clinical use. This notebook is an ML engineering demonstration and must not be used for diagnosis or patient care.

### Real dataset
- Dataset: **PneumoniaMNIST**
- Modality: pediatric chest X-ray
- Task: binary classification — **normal vs pneumonia**
- Official split: **4,708 train / 524 validation / 624 test**
- Resolution used here: **28×28 grayscale**
- License: **CC BY 4.0**
- Official distribution: https://medmnist.com/
- Official archive: https://zenodo.org/records/10519652

### What this notebook demonstrates
- real external medical-image ingestion
- untouched official test set
- class-imbalance handling
- PyTorch CNN training with early stopping
- sensitivity, specificity, precision, F1, balanced accuracy and ROC-AUC
- validation-only temperature calibration
- confidence-based human-review policy
- MC-dropout uncertainty
- Grad-CAM explanation
- corruption stress testing
- reproducibility and integrity checks

## 1. Setup and reproducibility

The notebook installs MedMNIST automatically if needed, fixes random seeds, and selects GPU when available. The executed GitHub version is produced by a repository workflow so the code and outputs remain together.

In [1]:
import sys, subprocess, random, time, io, warnings
from pathlib import Path

try:
    import medmnist
except ImportError:
    subprocess.check_call([
        sys.executable, "-m", "pip", "install", "-q", "medmnist>=3.0.2"
    ])
    import medmnist

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset
from torchvision import transforms

from medmnist import INFO, PneumoniaMNIST
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    log_loss,
)

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.set_num_threads(min(4, max(1, torch.get_num_threads())))

print("PyTorch:", torch.__version__)
print("MedMNIST:", medmnist.__version__)
print("Device:", DEVICE)
print("Seed:", SEED)

PyTorch: 2.14.1+cpu
MedMNIST: 3.0.2
Device: cpu
Seed: 42

## 2. Load the real PneumoniaMNIST dataset

The official MedMNIST API downloads the dataset and preserves its predefined train/validation/test split. The test set is not used for model fitting, early stopping, threshold selection, or temperature calibration.

In [2]:
DATA_ROOT = Path("data/medmnist")
DATA_ROOT.mkdir(parents=True, exist_ok=True)

transform = transforms.ToTensor()

train_dataset = PneumoniaMNIST(
    split="train",
    transform=transform,
    download=True,
    root=str(DATA_ROOT),
    size=28,
)
val_dataset = PneumoniaMNIST(
    split="val",
    transform=transform,
    download=True,
    root=str(DATA_ROOT),
    size=28,
)
test_dataset = PneumoniaMNIST(
    split="test",
    transform=transform,
    download=True,
    root=str(DATA_ROOT),
    size=28,
)

info = INFO["pneumoniamnist"]
CLASS_NAMES = [info["label"]["0"], info["label"]["1"]]

def labels_from_dataset(dataset):
    return np.asarray(dataset.labels).reshape(-1).astype(int)

y_train_np = labels_from_dataset(train_dataset)
y_val_np = labels_from_dataset(val_dataset)
y_test_np = labels_from_dataset(test_dataset)

split_summary = pd.DataFrame({
    "split": ["train", "validation", "test"],
    "rows": [len(train_dataset), len(val_dataset), len(test_dataset)],
    "normal": [
        int((y_train_np == 0).sum()),
        int((y_val_np == 0).sum()),
        int((y_test_np == 0).sum()),
    ],
    "pneumonia": [
        int((y_train_np == 1).sum()),
        int((y_val_np == 1).sum()),
        int((y_test_np == 1).sum()),
    ],
})

display(split_summary)
print("Class names:", CLASS_NAMES)
print("Official task:", info["task"])
print("License:", info["license"])

  0%|          | 0.00/4.17M [00:00<?, ?B/s]

  1%|          | 32.8k/4.17M [00:00<00:18, 226kB/s]

  2%|▏         | 65.5k/4.17M [00:00<00:18, 227kB/s]

  2%|▏         | 98.3k/4.17M [00:00<00:17, 229kB/s]

  4%|▍         | 164k/4.17M [00:00<00:12, 325kB/s]

  5%|▍         | 197k/4.17M [00:00<00:13, 289kB/s]

  7%|▋         | 295k/4.17M [00:00<00:09, 423kB/s]

  9%|▉         | 393k/4.17M [00:01<00:07, 507kB/s]

 11%|█         | 459k/4.17M [00:01<00:07, 489kB/s]

 13%|█▎        | 557k/4.17M [00:01<00:06, 548kB/s]

 16%|█▋        | 688k/4.17M [00:01<00:05, 658kB/s]

 19%|█▉        | 786k/4.17M [00:01<00:05, 664kB/s]

 23%|██▎       | 950k/4.17M [00:01<00:03, 806kB/s]

 26%|██▌       | 1.08M/4.17M [00:01<00:03, 836kB/s]

 28%|██▊       | 1.18M/4.17M [00:02<00:03, 788kB/s]

 31%|███▏      | 1.31M/4.17M [00:02<00:03, 823kB/s]

 34%|███▍      | 1.41M/4.17M [00:02<00:03, 779kB/s]

 36%|███▌      | 1.51M/4.17M [00:02<00:03, 748kB/s]

 38%|███▊      | 1.61M/4.17M [00:02<00:03, 727kB/s]

 42%|████▏     | 1.74M/4.17M [00:02<00:03, 780kB/s]

 45%|████▍     | 1.87M/4.17M [00:02<00:02, 817kB/s]

 47%|████▋     | 1.97M/4.17M [00:03<00:02, 774kB/s]

 50%|█████     | 2.10M/4.17M [00:03<00:02, 813kB/s]

 53%|█████▎    | 2.20M/4.17M [00:03<00:02, 772kB/s]

 55%|█████▍    | 2.29M/4.17M [00:03<00:02, 745kB/s]

 57%|█████▋    | 2.39M/4.17M [00:03<00:02, 726kB/s]

 60%|█████▉    | 2.49M/4.17M [00:03<00:02, 711kB/s]

 63%|██████▎   | 2.62M/4.17M [00:03<00:02, 768kB/s]

 68%|██████▊   | 2.82M/4.17M [00:04<00:01, 945kB/s]

 70%|██████▉   | 2.92M/4.17M [00:04<00:01, 866kB/s]

 72%|███████▏  | 3.01M/4.17M [00:04<00:01, 808kB/s]

 75%|███████▌  | 3.15M/4.17M [00:04<00:01, 837kB/s]

 79%|███████▉  | 3.31M/4.17M [00:04<00:00, 925kB/s]

 83%|████████▎ | 3.47M/4.17M [00:04<00:00, 986kB/s]

 86%|████████▋ | 3.60M/4.17M [00:04<00:00, 961kB/s]

 89%|████████▉ | 3.70M/4.17M [00:05<00:00, 876kB/s]

 91%|█████████ | 3.80M/4.17M [00:05<00:00, 818kB/s]

 94%|█████████▍| 3.93M/4.17M [00:05<00:00, 843kB/s]

 97%|█████████▋| 4.03M/4.17M [00:05<00:00, 794kB/s]

 99%|█████████▉| 4.13M/4.17M [00:05<00:00, 760kB/s]

100%|██████████| 4.17M/4.17M [00:05<00:00, 739kB/s]

        split  rows  normal  pneumonia
0       train  4708    1214       3494
1  validation   524     135        389
2        test   624     234        390

Class names: ['normal', 'pneumonia']
Official task: binary-class
License: CC BY 4.0

## 3. Inspect genuine chest X-rays

These examples come directly from the real training split. They are intentionally shown before modelling so the project documents the actual input domain rather than treating the dataset as an abstract tensor.

In [3]:
fig, axes = plt.subplots(2, 5, figsize=(11, 5))

for row, class_index in enumerate([0, 1]):
    indices = np.where(y_train_np == class_index)[0][:5]
    for col, idx in enumerate(indices):
        image, label = train_dataset[int(idx)]
        axes[row, col].imshow(image.squeeze(0), cmap="gray")
        axes[row, col].set_title(CLASS_NAMES[class_index])
        axes[row, col].axis("off")

plt.suptitle("Real PneumoniaMNIST training images")
plt.tight_layout()
plt.show()

class_counts = pd.Series(y_train_np).value_counts().sort_index()
plt.figure(figsize=(6, 4))
plt.bar(CLASS_NAMES, class_counts.values)
plt.title("Training-set class balance")
plt.ylabel("Images")
plt.show()

## 4. Data loaders and imbalance-aware loss

PneumoniaMNIST is class-imbalanced, so the training loss uses weights computed **only from the training labels**. Validation and test examples remain untouched.

In [4]:
BATCH_SIZE = 128

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=0,
)
val_loader = DataLoader(
    val_dataset,
    batch_size=256,
    shuffle=False,
    num_workers=0,
)
test_loader = DataLoader(
    test_dataset,
    batch_size=256,
    shuffle=False,
    num_workers=0,
)

counts = np.bincount(y_train_np, minlength=2)
class_weights_np = len(y_train_np) / (2.0 * counts)
class_weights = torch.tensor(
    class_weights_np, dtype=torch.float32, device=DEVICE
)

print("Training class counts:", dict(zip(CLASS_NAMES, counts.tolist())))
print("Loss class weights:", dict(zip(CLASS_NAMES, class_weights_np.round(4))))

Training class counts: {'normal': 1214, 'pneumonia': 3494}
Loss class weights: {'normal': np.float64(1.939), 'pneumonia': np.float64(0.6737)}

## 5. Compact PyTorch CNN

The network is intentionally small enough to train quickly on CPU while still supporting dropout-based uncertainty and Grad-CAM.

In [5]:
class PneumoniaCNN(nn.Module):
    def __init__(self, dropout=0.30):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1, 24, 3, padding=1),
            nn.BatchNorm2d(24),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(24, 48, 3, padding=1),
            nn.BatchNorm2d(48),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(48, 96, 3, padding=1),
            nn.BatchNorm2d(96),
            nn.ReLU(),
        )
        self.pool = nn.AdaptiveAvgPool2d((4, 4))
        self.dropout = nn.Dropout(dropout)
        self.classifier = nn.Linear(96 * 4 * 4, 2)

    def forward(self, x):
        x = self.features(x)
        x = self.pool(x)
        x = x.flatten(1)
        x = self.dropout(x)
        return self.classifier(x)

model = PneumoniaCNN(dropout=0.30).to(DEVICE)
criterion = nn.CrossEntropyLoss(weight=class_weights)
optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=1e-3,
    weight_decay=1e-4,
)

print(model)
print("Trainable parameters:", sum(p.numel() for p in model.parameters() if p.requires_grad))

PneumoniaCNN(
  (features): Sequential(
    (0): Conv2d(1, 24, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(24, eps=1e-05, momentum=0.1, affine=True, bias=True, track_running_stats=True)
    (2): ReLU()
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (4): Conv2d(24, 48, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (5): BatchNorm2d(48, eps=1e-05, momentum=0.1, affine=True, bias=True, track_running_stats=True)
    (6): ReLU()
    (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (8): Conv2d(48, 96, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, bias=True, track_running_stats=True)
    (10): ReLU()
  )
  (pool): AdaptiveAvgPool2d(output_size=(4, 4))
  (dropout): Dropout(p=0.3, inplace=False)
  (classifier): Linear(in_features=1536, out_features=2, bias=True)
)
Trainable parameters: 55634

## 6. Training with validation-only early stopping

The best model checkpoint is selected only from validation loss. The official test split remains sealed until final evaluation.

In [6]:
def evaluate_loss(model, loader):
    model.eval()
    total_loss = 0.0
    total_rows = 0

    with torch.no_grad():
        for images, labels in loader:
            images = images.to(DEVICE)
            labels = labels.view(-1).long().to(DEVICE)
            logits = model(images)
            loss = criterion(logits, labels)
            total_loss += loss.item() * len(labels)
            total_rows += len(labels)

    return total_loss / total_rows

best_state = None
best_val_loss = float("inf")
patience = 5
epochs_without_improvement = 0
history = []

MAX_EPOCHS = 20

for epoch in range(1, MAX_EPOCHS + 1):
    model.train()
    train_loss_sum = 0.0
    train_rows = 0

    for images, labels in train_loader:
        images = images.to(DEVICE)
        labels = labels.view(-1).long().to(DEVICE)

        optimizer.zero_grad(set_to_none=True)
        logits = model(images)
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()

        train_loss_sum += loss.item() * len(labels)
        train_rows += len(labels)

    train_loss = train_loss_sum / train_rows
    val_loss = evaluate_loss(model, val_loader)

    history.append({
        "epoch": epoch,
        "train_loss": train_loss,
        "val_loss": val_loss,
    })

    print(
        f"epoch={epoch:02d} "
        f"train_loss={train_loss:.4f} "
        f"val_loss={val_loss:.4f}"
    )

    if val_loss < best_val_loss - 1e-4:
        best_val_loss = val_loss
        best_state = {
            key: value.detach().cpu().clone()
            for key, value in model.state_dict().items()
        }
        epochs_without_improvement = 0
    else:
        epochs_without_improvement += 1

    if epochs_without_improvement >= patience:
        print("Early stopping triggered.")
        break

model.load_state_dict(best_state)
model.to(DEVICE)
model.eval()

history_df = pd.DataFrame(history)
history_df.plot(
    x="epoch",
    y=["train_loss", "val_loss"],
    figsize=(8, 4),
    marker="o",
)
plt.title("Real-data training history")
plt.ylabel("Weighted cross-entropy loss")
plt.show()

print("Best validation loss:", round(best_val_loss, 4))
print("Epochs trained:", len(history_df))

epoch=01 train_loss=0.3166 val_loss=2.3867

epoch=02 train_loss=0.1424 val_loss=0.1312

epoch=03 train_loss=0.1219 val_loss=0.1414

epoch=04 train_loss=0.1066 val_loss=0.1273

epoch=05 train_loss=0.0923 val_loss=0.0944

epoch=06 train_loss=0.0889 val_loss=0.3928

epoch=07 train_loss=0.0738 val_loss=0.0874

epoch=08 train_loss=0.0652 val_loss=0.0876

epoch=09 train_loss=0.0631 val_loss=0.6277

epoch=10 train_loss=0.0594 val_loss=0.1761

epoch=11 train_loss=0.0465 val_loss=0.0918

epoch=12 train_loss=0.0421 val_loss=0.1036
Early stopping triggered.
Best validation loss: 0.0874
Epochs trained: 12

## 7. Untouched test evaluation

For a medical classification task, accuracy alone is insufficient. The notebook reports:
- sensitivity (recall for pneumonia),
- specificity (recall for normal),
- precision,
- F1,
- balanced accuracy,
- ROC-AUC,
- and confusion matrix.

In [7]:
def collect_logits(model, loader):
    model.eval()
    logits_list = []
    labels_list = []

    with torch.no_grad():
        for images, labels in loader:
            logits = model(images.to(DEVICE)).cpu()
            logits_list.append(logits)
            labels_list.append(labels.view(-1).long())

    return torch.cat(logits_list), torch.cat(labels_list)

def softmax_numpy(logits, temperature=1.0):
    x = np.asarray(logits, dtype=float) / float(temperature)
    x = x - x.max(axis=1, keepdims=True)
    exp_x = np.exp(x)
    return exp_x / exp_x.sum(axis=1, keepdims=True)

def classification_metrics(labels, probabilities):
    labels = np.asarray(labels).astype(int)
    probabilities = np.asarray(probabilities)
    predictions = probabilities.argmax(axis=1)

    tn, fp, fn, tp = confusion_matrix(labels, predictions).ravel()

    return {
        "accuracy": accuracy_score(labels, predictions),
        "balanced_accuracy": balanced_accuracy_score(labels, predictions),
        "precision_pneumonia": precision_score(labels, predictions, zero_division=0),
        "sensitivity_pneumonia": recall_score(labels, predictions, pos_label=1),
        "specificity_normal": tn / (tn + fp),
        "f1_pneumonia": f1_score(labels, predictions, pos_label=1),
        "roc_auc": roc_auc_score(labels, probabilities[:, 1]),
        "nll": log_loss(labels, probabilities),
    }

val_logits, val_labels = collect_logits(model, val_loader)
test_logits, test_labels = collect_logits(model, test_loader)

test_probs_uncal = torch.softmax(test_logits, dim=1).numpy()
test_labels_np = test_labels.numpy()

test_metrics = classification_metrics(test_labels_np, test_probs_uncal)
display(pd.DataFrame([test_metrics]).round(4))

test_predictions = test_probs_uncal.argmax(axis=1)
cm = confusion_matrix(test_labels_np, test_predictions)

fig, ax = plt.subplots(figsize=(5, 4))
im = ax.imshow(cm, cmap="Blues")
ax.set_title("PneumoniaMNIST test confusion matrix")
ax.set_xlabel("Predicted")
ax.set_ylabel("Actual")
ax.set_xticks([0, 1], CLASS_NAMES)
ax.set_yticks([0, 1], CLASS_NAMES)
for i in range(2):
    for j in range(2):
        ax.text(j, i, int(cm[i, j]), ha="center", va="center")
plt.colorbar(im, ax=ax)
plt.tight_layout()
plt.show()

,accuracy,balanced_accuracy,precision_pneumonia,sensitivity_pneumonia,specificity_normal,f1_pneumonia,roc_auc,nll
0,0.8574,0.8132,0.8195,0.9897,0.6368,0.8966,0.9613,0.443

## 8. Validation-only probability calibration

Temperature scaling is selected using **validation logits only**. Calibration is then reported once on the untouched test set.

In [8]:
def expected_calibration_error(probabilities, labels, bins=10):
    probabilities = np.asarray(probabilities)
    labels = np.asarray(labels)
    confidence = probabilities.max(axis=1)
    prediction = probabilities.argmax(axis=1)

    ece = 0.0
    edges = np.linspace(0, 1, bins + 1)

    for left, right in zip(edges[:-1], edges[1:]):
        mask = (confidence > left) & (confidence <= right)
        if not mask.any():
            continue
        accuracy = (prediction[mask] == labels[mask]).mean()
        avg_confidence = confidence[mask].mean()
        ece += mask.mean() * abs(accuracy - avg_confidence)

    return float(ece)

val_logits_np = val_logits.numpy()
val_labels_np = val_labels.numpy()
test_logits_np = test_logits.numpy()

temperature_grid = np.linspace(0.5, 4.0, 141)
val_nll = [
    log_loss(val_labels_np, softmax_numpy(val_logits_np, temperature))
    for temperature in temperature_grid
]
best_temperature = float(
    temperature_grid[int(np.argmin(val_nll))]
)

test_probs_cal = softmax_numpy(test_logits_np, best_temperature)

calibration_report = pd.DataFrame([{
    "temperature": best_temperature,
    "ECE_before": expected_calibration_error(
        test_probs_uncal, test_labels_np
    ),
    "ECE_after": expected_calibration_error(
        test_probs_cal, test_labels_np
    ),
    "NLL_before": log_loss(test_labels_np, test_probs_uncal),
    "NLL_after": log_loss(test_labels_np, test_probs_cal),
}])

display(calibration_report.round(4))

   temperature  ECE_before  ECE_after  NLL_before  NLL_after
0         0.95      0.0844     0.0872       0.443     0.4593

## 9. Confidence-based human review

The model is allowed to abstain. A confidence threshold is selected on the validation set under a minimum 75% automatic-coverage constraint, then applied once to the test set.

This is an engineering demonstration of selective prediction, **not a clinical triage policy**.

In [9]:
val_probs_cal = softmax_numpy(val_logits_np, best_temperature)
val_confidence = val_probs_cal.max(axis=1)
val_prediction = val_probs_cal.argmax(axis=1)

policy_rows = []
for threshold in np.linspace(0.50, 0.95, 91):
    accepted = val_confidence >= threshold
    coverage = accepted.mean()
    selective_accuracy = (
        (val_prediction[accepted] == val_labels_np[accepted]).mean()
        if accepted.any() else np.nan
    )
    policy_rows.append({
        "threshold": threshold,
        "coverage": coverage,
        "selective_accuracy": selective_accuracy,
    })

policy_df = pd.DataFrame(policy_rows)
eligible = policy_df[policy_df["coverage"] >= 0.75]

chosen = eligible.sort_values(
    ["selective_accuracy", "threshold"],
    ascending=[False, False],
).iloc[0]

REVIEW_THRESHOLD = float(chosen["threshold"])

test_confidence = test_probs_cal.max(axis=1)
test_prediction_cal = test_probs_cal.argmax(axis=1)
accepted = test_confidence >= REVIEW_THRESHOLD
errors = test_prediction_cal != test_labels_np

selective_report = pd.DataFrame([{
    "review_threshold": REVIEW_THRESHOLD,
    "automatic_coverage": accepted.mean(),
    "review_rate": (~accepted).mean(),
    "accuracy_on_accepted": (
        (test_prediction_cal[accepted] == test_labels_np[accepted]).mean()
        if accepted.any() else np.nan
    ),
    "test_errors_escalated": (
        ((~accepted) & errors).sum() / errors.sum()
        if errors.sum() else 0.0
    ),
}])

display(selective_report.round(4))

,review_threshold,automatic_coverage,review_rate,accuracy_on_accepted,test_errors_escalated
0,0.94,0.7837,0.2163,0.9346,0.6404

## 10. MC-dropout uncertainty

Repeated dropout-enabled forward passes provide a simple uncertainty heuristic. It is useful for ranking uncertain examples, but it is **not** a calibrated clinical confidence interval.

In [10]:
def mc_dropout_probabilities(model, loader, passes=25):
    model.train()
    all_images = []
    all_labels = []

    for images, labels in loader:
        all_images.append(images)
        all_labels.append(labels.view(-1))

    images = torch.cat(all_images).to(DEVICE)
    labels = torch.cat(all_labels).numpy()

    draws = []
    with torch.no_grad():
        for _ in range(passes):
            logits = model(images)
            draws.append(
                torch.softmax(logits, dim=1).cpu().numpy()
            )

    model.eval()
    draws = np.stack(draws, axis=0)

    return labels, draws.mean(axis=0), draws.std(axis=0)

mc_labels, mc_mean, mc_std = mc_dropout_probabilities(
    model, test_loader, passes=25
)

mc_prediction = mc_mean.argmax(axis=1)
uncertainty = mc_std.max(axis=1)
correct = mc_prediction == mc_labels

uncertainty_report = pd.DataFrame({
    "true_label": mc_labels,
    "prediction": mc_prediction,
    "confidence": mc_mean.max(axis=1),
    "mc_uncertainty": uncertainty,
    "correct": correct,
})

display(
    uncertainty_report
    .sort_values("mc_uncertainty", ascending=False)
    .head(12)
    .round(4)
)

print(
    "Mean uncertainty — correct:",
    round(float(uncertainty_report.loc[correct, "mc_uncertainty"].mean()), 4)
)
print(
    "Mean uncertainty — incorrect:",
    round(float(uncertainty_report.loc[~correct, "mc_uncertainty"].mean()), 4)
)

     true_label  prediction  confidence  mc_uncertainty  correct
278           0           0      0.5293          0.1576     True
102           1           0      0.6666          0.1523    False
199           0           0      0.5226          0.1475     True
239           0           1      0.5555          0.1405    False
394           0           0      0.6067          0.1373     True
72            0           0      0.6214          0.1372     True
255           0           0      0.6535          0.1369     True
469           0           1      0.7400          0.1348    False
126           0           1      0.6127          0.1314    False
128           0           1      0.6133          0.1312    False
85            0           0      0.5121          0.1271     True
231           0           0      0.5423          0.1257     True

Mean uncertainty — correct: 0.0154
Mean uncertainty — incorrect: 0.0623

## 11. Grad-CAM on a real test X-ray

Grad-CAM highlights image regions that influenced the selected class score. It is a model-behaviour visualization, not proof of clinically valid reasoning.

In [11]:
def gradcam_heatmap(model, image_tensor, target_class=None):
    activations = []
    gradients = []

    target_layer = model.features[8]  # final convolution

    def forward_hook(_module, _inputs, output):
        activations.append(output)

    def backward_hook(_module, _grad_input, grad_output):
        gradients.append(grad_output[0])

    fh = target_layer.register_forward_hook(forward_hook)
    bh = target_layer.register_full_backward_hook(backward_hook)

    try:
        model.eval()
        model.zero_grad(set_to_none=True)

        image_tensor = image_tensor.to(DEVICE)
        logits = model(image_tensor)

        if target_class is None:
            target_class = int(logits.argmax(dim=1).item())

        logits[0, target_class].backward()

        fmap = activations[-1]
        grad = gradients[-1]
        weights = grad.mean(dim=(2, 3), keepdim=True)

        cam = torch.relu((weights * fmap).sum(dim=1, keepdim=True))
        cam = F.interpolate(
            cam,
            size=image_tensor.shape[-2:],
            mode="bilinear",
            align_corners=False,
        )

        cam = cam[0, 0]
        cam = cam - cam.min()
        cam = cam / cam.max().clamp_min(1e-12)
        return cam.detach().cpu().numpy()

    finally:
        fh.remove()
        bh.remove()

# choose the most confident pneumonia prediction from the real test set
example_index = int(np.argmax(test_probs_cal[:, 1]))
example_image, example_label = test_dataset[example_index]
example_batch = example_image.unsqueeze(0)

heatmap = gradcam_heatmap(model, example_batch)

fig, axes = plt.subplots(1, 3, figsize=(10, 3.4))

axes[0].imshow(example_image.squeeze(0), cmap="gray")
axes[0].set_title("Real test X-ray")
axes[0].axis("off")

axes[1].imshow(heatmap, cmap="inferno")
axes[1].set_title("Grad-CAM")
axes[1].axis("off")

axes[2].imshow(example_image.squeeze(0), cmap="gray")
axes[2].imshow(heatmap, cmap="inferno", alpha=0.45)
axes[2].set_title("Overlay")
axes[2].axis("off")

plt.tight_layout()
plt.show()

true_index = int(np.asarray(example_label).reshape(-1)[0])
pred_index = int(test_prediction_cal[example_index])

print("True class:", CLASS_NAMES[true_index])
print("Predicted class:", CLASS_NAMES[pred_index])
print("Calibrated confidence:", round(float(test_confidence[example_index]), 4))

True class: pneumonia
Predicted class: pneumonia
Calibrated confidence: 1.0

## 12. Corruption stress test

A deployment-minded portfolio should test failure under input shift. This section adds moderate Gaussian noise to the **real test images** and measures degradation. The corrupted images are only a stress test; they are not primary training or evaluation data.

In [12]:
all_test_images = []
all_test_labels = []

for images, labels in test_loader:
    all_test_images.append(images)
    all_test_labels.append(labels.view(-1))

clean_images = torch.cat(all_test_images)
clean_labels = torch.cat(all_test_labels)

generator = torch.Generator().manual_seed(SEED + 1)
noise = torch.randn(
    clean_images.shape,
    generator=generator,
) * 0.12

corrupted_images = torch.clamp(
    clean_images * 0.85 + 0.075 + noise,
    0,
    1,
)

corrupted_loader = DataLoader(
    TensorDataset(corrupted_images, clean_labels),
    batch_size=256,
    shuffle=False,
)

corrupted_logits, corrupted_labels = collect_logits(
    model, corrupted_loader
)
corrupted_probs = torch.softmax(
    corrupted_logits, dim=1
).numpy()

corrupted_metrics = classification_metrics(
    corrupted_labels.numpy(),
    corrupted_probs,
)

robustness = pd.DataFrame([
    {"condition": "clean real test", **test_metrics},
    {"condition": "noise stress test", **corrupted_metrics},
])

display(
    robustness[
        [
            "condition",
            "accuracy",
            "balanced_accuracy",
            "sensitivity_pneumonia",
            "specificity_normal",
            "f1_pneumonia",
            "roc_auc",
        ]
    ].round(4)
)

robustness.plot.bar(
    x="condition",
    y=["balanced_accuracy", "roc_auc"],
    figsize=(7, 4),
    rot=0,
)
plt.ylim(0, 1)
plt.title("Performance under image corruption")
plt.show()

,condition,accuracy,balanced_accuracy,sensitivity_pneumonia,specificity_normal,f1_pneumonia,roc_auc
0,clean real test,0.8574,0.8132,0.9897,0.6368,0.8966,0.9613
1,noise stress test,0.3814,0.5043,0.0128,0.9957,0.0253,0.8672

## 13. Integrity checks and interview summary

The final assertions make notebook failures explicit instead of silently producing a polished-looking result.

> **Interview summary:** I trained a PyTorch CNN on the official real PneumoniaMNIST split, controlled class imbalance with train-only weights, kept validation and test roles separate, reported clinically relevant classification metrics, calibrated probabilities using validation data, added selective prediction, MC-dropout uncertainty, Grad-CAM, and a corruption stress test. I explicitly treat the result as research/engineering evidence rather than a medical device claim.

In [13]:
assert len(train_dataset) == 4708
assert len(val_dataset) == 524
assert len(test_dataset) == 624
assert set(np.unique(y_train_np)) == {0, 1}
assert test_logits.shape == (624, 2)
assert np.isfinite(test_probs_cal).all()
assert np.allclose(test_probs_cal.sum(axis=1), 1.0, atol=1e-6)
assert 0 <= test_metrics["roc_auc"] <= 1
assert 0 <= test_metrics["balanced_accuracy"] <= 1
assert heatmap.shape == (28, 28)
assert np.isfinite(heatmap).all()
assert 0 <= heatmap.min() <= heatmap.max() <= 1.0 + 1e-6

print("All real-data medical-AI integrity checks passed.")
print("Primary dataset: PneumoniaMNIST (real pediatric chest X-rays)")
print("Clinical use: prohibited — research/education only")

All real-data medical-AI integrity checks passed.
Primary dataset: PneumoniaMNIST (real pediatric chest X-rays)
Clinical use: prohibited — research/education only