# PyTorch Medical AI — Real PneumoniaMNIST Chest X-Ray Triage

**2026 portfolio edition · Real medical images · PyTorch · calibration · uncertainty · explainability**

[Open in Google Colab](https://colab.research.google.com/github/Jorgoluka100/uni_projects/blob/main/PyTorch_medical_AI_xray_diagnosis.ipynb)

> **Dataset:** PneumoniaMNIST from the official MedMNIST distribution. This notebook uses the official train/validation/test splits and **real chest X-ray images**. Synthetic images are not used for training or headline evaluation.

> **Safety:** MedMNIST is an educational/research benchmark and is **not intended for clinical use**. Nothing here is a diagnostic claim or medical device.

### What this notebook demonstrates
- real public medical-imaging data with provenance
- official train/validation/test split discipline
- flattened-pixel linear baseline vs CNN
- imbalance-aware PyTorch training + early stopping
- sensitivity/specificity, balanced accuracy, F1, ROC-AUC, PR-AUC, MCC, NLL and Brier score
- validation-only temperature scaling
- validation-only **illustrative sensitivity-constrained threshold**
- ROC/PR curves, confusion matrix and reliability diagram
- confidence-based human-review policy
- MC-dropout uncertainty
- Grad-CAM on a real test X-ray
- qualitative error gallery
- corruption stress testing
- inference/model-size profiling and integrity tests

**Official source:** https://medmnist.com/

## 1. Setup and reproducibility

In [1]:
import sys
import subprocess
import random
import time
import io
from pathlib import Path

try:
    import medmnist
except ImportError:
    subprocess.check_call([
        sys.executable, "-m", "pip", "install", "-q", "medmnist>=3.0.2"
    ])
    import medmnist

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset
from torchvision import transforms

from medmnist import INFO, PneumoniaMNIST
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    matthews_corrcoef,
    confusion_matrix,
    log_loss,
    brier_score_loss,
    roc_curve,
    precision_recall_curve,
)

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.set_num_threads(min(4, max(1, torch.get_num_threads())))

print("PyTorch:", torch.__version__)
print("MedMNIST:", medmnist.__version__)
print("Device:", DEVICE)
print("Seed:", SEED)

PyTorch: 2.14.1+cpu
MedMNIST: 3.0.2
Device: cpu
Seed: 42

## 2. Load the real PneumoniaMNIST dataset

MedMNIST provides fixed benchmark splits, so we do **not** reshuffle the data. This preserves comparability and keeps the test set completely untouched until final evaluation.

The 64×64 MedMNIST+ images are used here instead of the smallest 28×28 version so the notebook retains more spatial detail while remaining lightweight enough for CPU/Colab execution.

In [2]:
DATA_ROOT = Path("data/medmnist")
DATA_ROOT.mkdir(parents=True, exist_ok=True)

IMAGE_SIZE = 64
transform = transforms.ToTensor()

train_dataset = PneumoniaMNIST(
    split="train",
    transform=transform,
    download=True,
    root=str(DATA_ROOT),
    size=IMAGE_SIZE,
)
val_dataset = PneumoniaMNIST(
    split="val",
    transform=transform,
    download=True,
    root=str(DATA_ROOT),
    size=IMAGE_SIZE,
)
test_dataset = PneumoniaMNIST(
    split="test",
    transform=transform,
    download=True,
    root=str(DATA_ROOT),
    size=IMAGE_SIZE,
)

info = INFO["pneumoniamnist"]
CLASS_NAMES = [info["label"]["0"], info["label"]["1"]]

def labels_from_dataset(dataset):
    return np.asarray(dataset.labels).reshape(-1).astype(int)

y_train_np = labels_from_dataset(train_dataset)
y_val_np = labels_from_dataset(val_dataset)
y_test_np = labels_from_dataset(test_dataset)

split_summary = pd.DataFrame({
    "split": ["train", "validation", "test"],
    "rows": [len(train_dataset), len(val_dataset), len(test_dataset)],
    "normal": [
        int((y_train_np == 0).sum()),
        int((y_val_np == 0).sum()),
        int((y_test_np == 0).sum()),
    ],
    "pneumonia": [
        int((y_train_np == 1).sum()),
        int((y_val_np == 1).sum()),
        int((y_test_np == 1).sum()),
    ],
})

display(split_summary)
print("Image size:", IMAGE_SIZE, "x", IMAGE_SIZE)
print("Class names:", CLASS_NAMES)
print("Official task:", info["task"])
print("License:", info["license"])

  0%|          | 0.00/20.6M [00:00<?, ?B/s]

  0%|          | 32.8k/20.6M [00:00<01:44, 197kB/s]

  0%|          | 98.3k/20.6M [00:00<00:52, 393kB/s]

  1%|          | 164k/20.6M [00:00<00:42, 477kB/s]

  1%|          | 229k/20.6M [00:00<00:38, 524kB/s]

  1%|▏         | 295k/20.6M [00:00<00:36, 551kB/s]

  2%|▏         | 360k/20.6M [00:00<00:35, 567kB/s]

  2%|▏         | 426k/20.6M [00:00<00:34, 578kB/s]

  2%|▏         | 492k/20.6M [00:00<00:34, 585kB/s]

  3%|▎         | 623k/20.6M [00:01<00:25, 777kB/s]

  3%|▎         | 721k/20.6M [00:01<00:24, 813kB/s]

  4%|▍         | 819k/20.6M [00:01<00:23, 838kB/s]

  5%|▍         | 950k/20.6M [00:01<00:20, 944kB/s]

  5%|▌         | 1.05M/20.6M [00:01<00:21, 930kB/s]

  6%|▌         | 1.15M/20.6M [00:01<00:21, 919kB/s]

  6%|▌         | 1.25M/20.6M [00:01<00:21, 911kB/s]

  7%|▋         | 1.34M/20.6M [00:01<00:21, 909kB/s]

  7%|▋         | 1.44M/20.6M [00:01<00:21, 908kB/s]

  7%|▋         | 1.54M/20.6M [00:02<00:21, 907kB/s]

  8%|▊         | 1.67M/20.6M [00:02<00:19, 994kB/s]

  9%|▊         | 1.80M/20.6M [00:02<00:17, 1.06MB/s]

 10%|▉         | 1.97M/20.6M [00:02<00:15, 1.18MB/s]

 10%|█         | 2.13M/20.6M [00:02<00:14, 1.28MB/s]

 11%|█         | 2.26M/20.6M [00:02<00:14, 1.25MB/s]

 12%|█▏        | 2.39M/20.6M [00:02<00:14, 1.23MB/s]

 12%|█▏        | 2.52M/20.6M [00:02<00:14, 1.22MB/s]

 13%|█▎        | 2.65M/20.6M [00:02<00:14, 1.22MB/s]

 14%|█▎        | 2.79M/20.6M [00:03<00:14, 1.21MB/s]

 14%|█▍        | 2.92M/20.6M [00:03<00:14, 1.21MB/s]

 15%|█▍        | 3.05M/20.6M [00:03<00:14, 1.20MB/s]

 15%|█▌        | 3.18M/20.6M [00:03<00:14, 1.20MB/s]

 16%|█▌        | 3.31M/20.6M [00:03<00:14, 1.20MB/s]

 17%|█▋        | 3.44M/20.6M [00:03<00:14, 1.20MB/s]

 17%|█▋        | 3.57M/20.6M [00:03<00:14, 1.20MB/s]

 18%|█▊        | 3.70M/20.6M [00:03<00:18, 928kB/s]

 19%|█▊        | 3.83M/20.6M [00:03<00:16, 994kB/s]

 19%|█▉        | 3.96M/20.6M [00:04<00:15, 1.05MB/s]

 20%|█▉        | 4.10M/20.6M [00:04<00:15, 1.09MB/s]

 21%|██        | 4.23M/20.6M [00:04<00:14, 1.12MB/s]

 21%|██        | 4.36M/20.6M [00:04<00:14, 1.14MB/s]

 22%|██▏       | 4.49M/20.6M [00:04<00:13, 1.16MB/s]

 22%|██▏       | 4.62M/20.6M [00:04<00:13, 1.17MB/s]

 23%|██▎       | 4.75M/20.6M [00:04<00:13, 1.18MB/s]

 24%|██▍       | 4.95M/20.6M [00:04<00:11, 1.36MB/s]

 25%|██▍       | 5.14M/20.6M [00:04<00:10, 1.49MB/s]

 26%|██▌       | 5.31M/20.6M [00:05<00:10, 1.50MB/s]

 27%|██▋       | 5.47M/20.6M [00:05<00:10, 1.50MB/s]

 27%|██▋       | 5.64M/20.6M [00:05<00:12, 1.16MB/s]

 28%|██▊       | 5.80M/20.6M [00:05<00:11, 1.24MB/s]

 29%|██▉       | 5.96M/20.6M [00:05<00:11, 1.31MB/s]

 30%|██▉       | 6.13M/20.6M [00:05<00:13, 1.07MB/s]

 30%|███       | 6.26M/20.6M [00:05<00:13, 1.10MB/s]

 31%|███       | 6.39M/20.6M [00:06<00:12, 1.13MB/s]

 32%|███▏      | 6.52M/20.6M [00:06<00:12, 1.15MB/s]

 32%|███▏      | 6.65M/20.6M [00:06<00:12, 1.16MB/s]

 33%|███▎      | 6.78M/20.6M [00:06<00:11, 1.17MB/s]

 34%|███▎      | 6.91M/20.6M [00:06<00:11, 1.18MB/s]

 34%|███▍      | 7.05M/20.6M [00:06<00:14, 923kB/s]

 35%|███▍      | 7.18M/20.6M [00:06<00:13, 991kB/s]

 35%|███▌      | 7.31M/20.6M [00:06<00:12, 1.05MB/s]

 36%|███▌      | 7.44M/20.6M [00:07<00:12, 1.09MB/s]

 37%|███▋      | 7.57M/20.6M [00:07<00:11, 1.12MB/s]

 37%|███▋      | 7.70M/20.6M [00:07<00:11, 1.14MB/s]

 38%|███▊      | 7.83M/20.6M [00:07<00:11, 1.16MB/s]

 39%|███▊      | 7.96M/20.6M [00:07<00:10, 1.17MB/s]

 39%|███▉      | 8.09M/20.6M [00:07<00:10, 1.18MB/s]

 40%|███▉      | 8.22M/20.6M [00:07<00:10, 1.19MB/s]

 41%|████      | 8.36M/20.6M [00:07<00:10, 1.19MB/s]

 41%|████      | 8.49M/20.6M [00:07<00:10, 1.20MB/s]

 42%|████▏     | 8.62M/20.6M [00:08<00:10, 1.20MB/s]

 42%|████▏     | 8.75M/20.6M [00:08<00:12, 925kB/s]

 43%|████▎     | 8.88M/20.6M [00:08<00:11, 994kB/s]

 44%|████▎     | 9.01M/20.6M [00:08<00:11, 1.05MB/s]

 44%|████▍     | 9.14M/20.6M [00:08<00:10, 1.09MB/s]

 45%|████▌     | 9.27M/20.6M [00:08<00:10, 1.12MB/s]

 46%|████▌     | 9.40M/20.6M [00:08<00:09, 1.15MB/s]

 46%|████▋     | 9.54M/20.6M [00:08<00:09, 1.16MB/s]

 47%|████▋     | 9.67M/20.6M [00:09<00:09, 1.17MB/s]

 48%|████▊     | 9.80M/20.6M [00:09<00:09, 1.18MB/s]

 48%|████▊     | 9.96M/20.6M [00:09<00:08, 1.27MB/s]

 49%|████▉     | 10.1M/20.6M [00:09<00:07, 1.34MB/s]

 50%|████▉     | 10.3M/20.6M [00:09<00:07, 1.38MB/s]

 51%|█████     | 10.5M/20.6M [00:09<00:07, 1.42MB/s]

 52%|█████▏    | 10.6M/20.6M [00:09<00:09, 1.11MB/s]

 52%|█████▏    | 10.8M/20.6M [00:09<00:07, 1.28MB/s]

 53%|█████▎    | 11.0M/20.6M [00:09<00:07, 1.33MB/s]

 54%|█████▍    | 11.1M/20.6M [00:10<00:06, 1.38MB/s]

 55%|█████▍    | 11.3M/20.6M [00:10<00:08, 1.11MB/s]

 55%|█████▌    | 11.4M/20.6M [00:10<00:08, 1.13MB/s]

 56%|█████▌    | 11.6M/20.6M [00:10<00:07, 1.15MB/s]

 57%|█████▋    | 11.7M/20.6M [00:10<00:07, 1.16MB/s]

 57%|█████▋    | 11.8M/20.6M [00:10<00:09, 922kB/s]

 59%|█████▊    | 12.1M/20.6M [00:10<00:07, 1.20MB/s]

 59%|█████▉    | 12.2M/20.6M [00:11<00:06, 1.27MB/s]

 60%|██████    | 12.4M/20.6M [00:11<00:06, 1.33MB/s]

 61%|██████    | 12.6M/20.6M [00:11<00:05, 1.38MB/s]

 62%|██████▏   | 12.7M/20.6M [00:11<00:05, 1.41MB/s]

 62%|██████▏   | 12.9M/20.6M [00:11<00:06, 1.12MB/s]

 63%|██████▎   | 13.0M/20.6M [00:11<00:06, 1.14MB/s]

 64%|██████▍   | 13.1M/20.6M [00:11<00:06, 1.15MB/s]

 64%|██████▍   | 13.3M/20.6M [00:12<00:07, 921kB/s]

 65%|██████▌   | 13.4M/20.6M [00:12<00:07, 985kB/s]

 66%|██████▌   | 13.5M/20.6M [00:12<00:06, 1.04MB/s]

 66%|██████▋   | 13.7M/20.6M [00:12<00:06, 1.08MB/s]

 67%|██████▋   | 13.8M/20.6M [00:12<00:06, 1.11MB/s]

 68%|██████▊   | 13.9M/20.6M [00:12<00:05, 1.13MB/s]

 68%|██████▊   | 14.1M/20.6M [00:12<00:05, 1.15MB/s]

 69%|██████▉   | 14.2M/20.6M [00:12<00:05, 1.17MB/s]

 70%|██████▉   | 14.4M/20.6M [00:12<00:04, 1.26MB/s]

 70%|███████   | 14.5M/20.6M [00:13<00:04, 1.33MB/s]

 71%|███████   | 14.7M/20.6M [00:13<00:04, 1.38MB/s]

 72%|███████▏  | 14.8M/20.6M [00:13<00:05, 1.09MB/s]

 73%|███████▎  | 15.0M/20.6M [00:13<00:05, 1.12MB/s]

 73%|███████▎  | 15.1M/20.6M [00:13<00:04, 1.14MB/s]

 74%|███████▍  | 15.2M/20.6M [00:13<00:04, 1.15MB/s]

 75%|███████▍  | 15.4M/20.6M [00:13<00:04, 1.16MB/s]

 75%|███████▌  | 15.5M/20.6M [00:13<00:04, 1.17MB/s]

 76%|███████▌  | 15.6M/20.6M [00:14<00:04, 1.18MB/s]

 76%|███████▋  | 15.8M/20.6M [00:14<00:04, 1.19MB/s]

 77%|███████▋  | 15.9M/20.6M [00:14<00:03, 1.19MB/s]

 78%|███████▊  | 16.0M/20.6M [00:14<00:04, 921kB/s]

 78%|███████▊  | 16.2M/20.6M [00:14<00:04, 989kB/s]

 79%|███████▉  | 16.3M/20.6M [00:14<00:04, 1.04MB/s]

 80%|███████▉  | 16.4M/20.6M [00:14<00:03, 1.08MB/s]

 80%|████████  | 16.6M/20.6M [00:14<00:03, 1.20MB/s]

 81%|████████▏ | 16.7M/20.6M [00:15<00:03, 1.28MB/s]

 82%|████████▏ | 16.9M/20.6M [00:15<00:02, 1.34MB/s]

 83%|████████▎ | 17.1M/20.6M [00:15<00:02, 1.39MB/s]

 84%|████████▎ | 17.2M/20.6M [00:15<00:03, 1.10MB/s]

 84%|████████▍ | 17.4M/20.6M [00:15<00:02, 1.12MB/s]

 85%|████████▍ | 17.5M/20.6M [00:15<00:02, 1.14MB/s]

 86%|████████▌ | 17.6M/20.6M [00:15<00:02, 1.16MB/s]

 86%|████████▌ | 17.8M/20.6M [00:15<00:02, 1.17MB/s]

 87%|████████▋ | 17.9M/20.6M [00:16<00:02, 1.18MB/s]

 87%|████████▋ | 18.0M/20.6M [00:16<00:02, 1.18MB/s]

 88%|████████▊ | 18.2M/20.6M [00:16<00:02, 1.19MB/s]

 89%|████████▊ | 18.3M/20.6M [00:16<00:01, 1.19MB/s]

 89%|████████▉ | 18.4M/20.6M [00:16<00:01, 1.20MB/s]

 90%|█████████ | 18.5M/20.6M [00:16<00:01, 1.20MB/s]

 91%|█████████ | 18.7M/20.6M [00:16<00:01, 1.20MB/s]

 91%|█████████▏| 18.8M/20.6M [00:16<00:01, 1.20MB/s]

 92%|█████████▏| 18.9M/20.6M [00:16<00:01, 1.20MB/s]

 93%|█████████▎| 19.1M/20.6M [00:16<00:01, 1.20MB/s]

 93%|█████████▎| 19.2M/20.6M [00:17<00:01, 1.20MB/s]

 94%|█████████▍| 19.3M/20.6M [00:17<00:01, 1.20MB/s]

 94%|█████████▍| 19.5M/20.6M [00:17<00:00, 1.20MB/s]

 95%|█████████▌| 19.6M/20.6M [00:17<00:00, 1.20MB/s]

 96%|█████████▌| 19.7M/20.6M [00:17<00:00, 1.20MB/s]

 96%|█████████▋| 19.9M/20.6M [00:17<00:00, 1.20MB/s]

 97%|█████████▋| 20.0M/20.6M [00:17<00:00, 1.29MB/s]

 98%|█████████▊| 20.2M/20.6M [00:17<00:00, 1.26MB/s]

 98%|█████████▊| 20.3M/20.6M [00:17<00:00, 1.24MB/s]

 99%|█████████▉| 20.4M/20.6M [00:18<00:00, 949kB/s]

100%|██████████| 20.6M/20.6M [00:18<00:00, 1.13MB/s]

        split  rows  normal  pneumonia
0       train  4708    1214       3494
1  validation   524     135        389
2        test   624     234        390

Image size: 64 x 64
Class names: ['normal', 'pneumonia']
Official task: binary-class
License: CC BY 4.0

## 3. Inspect genuine chest X-rays and class balance

In [3]:
fig, axes = plt.subplots(2, 5, figsize=(12, 5.5))

for row, class_index in enumerate([0, 1]):
    indices = np.where(y_train_np == class_index)[0][:5]
    for col, idx in enumerate(indices):
        image, _ = train_dataset[int(idx)]
        axes[row, col].imshow(image.squeeze(0), cmap="gray")
        axes[row, col].set_title(CLASS_NAMES[class_index])
        axes[row, col].axis("off")

plt.suptitle("Real PneumoniaMNIST training images")
plt.tight_layout()
plt.show()

class_counts = pd.Series(y_train_np).value_counts().sort_index()

plt.figure(figsize=(6, 4))
plt.bar(CLASS_NAMES, class_counts.values)
plt.title("Training-set class balance")
plt.ylabel("Images")
plt.show()

## 4. Data loaders and imbalance-aware loss

The training set contains more pneumonia images than normal images, so inverse-frequency class weights are used in the CNN loss. The validation/test distributions are never used to calculate training weights.

In [4]:
BATCH_SIZE = 128

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=0,
)
val_loader = DataLoader(
    val_dataset,
    batch_size=256,
    shuffle=False,
    num_workers=0,
)
test_loader = DataLoader(
    test_dataset,
    batch_size=256,
    shuffle=False,
    num_workers=0,
)

counts = np.bincount(y_train_np, minlength=2)
class_weights_np = len(y_train_np) / (2.0 * counts)
class_weights = torch.tensor(
    class_weights_np,
    dtype=torch.float32,
    device=DEVICE,
)

print("Training class counts:", dict(zip(CLASS_NAMES, counts.tolist())))
print("Loss class weights:", dict(zip(CLASS_NAMES, class_weights_np.round(4))))

Training class counts: {'normal': 1214, 'pneumonia': 3494}
Loss class weights: {'normal': np.float64(1.939), 'pneumonia': np.float64(0.6737)}

## 5. Strong linear-image baseline

A CNN should earn its complexity. A balanced logistic-regression baseline is trained on **flattened real training pixels** and evaluated later on the same untouched test set.

In [5]:
def dataset_to_numpy(dataset):
    images = []
    labels = []

    for image, label in dataset:
        images.append(image.numpy().reshape(-1))
        labels.append(int(np.asarray(label).reshape(-1)[0]))

    return (
        np.asarray(images, dtype=np.float32),
        np.asarray(labels, dtype=np.int64),
    )

X_train_flat, y_train_flat = dataset_to_numpy(train_dataset)
X_val_flat, y_val_flat = dataset_to_numpy(val_dataset)
X_test_flat, y_test_flat = dataset_to_numpy(test_dataset)

pixel_baseline = LogisticRegression(
    max_iter=250,
    solver="liblinear",
    class_weight="balanced",
    C=0.5,
    random_state=SEED,
)
pixel_baseline.fit(X_train_flat, y_train_flat)

baseline_test_positive = pixel_baseline.predict_proba(X_test_flat)[:, 1]
baseline_test_probs = np.column_stack([
    1.0 - baseline_test_positive,
    baseline_test_positive,
])

print("Pixel baseline fitted:", X_train_flat.shape)

Pixel baseline fitted: (4708, 4096)

## 6. Compact PyTorch CNN

The CNN is deliberately small enough to understand and defend line-by-line in an interview. Adaptive pooling keeps the classifier independent of the exact input spatial size.

In [6]:
class PneumoniaCNN(nn.Module):
    def __init__(self, dropout=0.30):
        super().__init__()

        self.features = nn.Sequential(
            nn.Conv2d(1, 24, 3, padding=1),
            nn.BatchNorm2d(24),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(24, 48, 3, padding=1),
            nn.BatchNorm2d(48),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(48, 96, 3, padding=1),
            nn.BatchNorm2d(96),
            nn.ReLU(),
        )

        self.pool = nn.AdaptiveAvgPool2d((4, 4))
        self.dropout = nn.Dropout(dropout)
        self.classifier = nn.Linear(96 * 4 * 4, 2)

    def forward(self, x):
        x = self.features(x)
        x = self.pool(x)
        x = x.flatten(1)
        x = self.dropout(x)
        return self.classifier(x)

model = PneumoniaCNN(dropout=0.30).to(DEVICE)

criterion = nn.CrossEntropyLoss(weight=class_weights)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=1e-3,
    weight_decay=1e-4,
)

print(model)
print(
    "Trainable parameters:",
    sum(p.numel() for p in model.parameters() if p.requires_grad),
)

PneumoniaCNN(
  (features): Sequential(
    (0): Conv2d(1, 24, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(24, eps=1e-05, momentum=0.1, affine=True, bias=True, track_running_stats=True)
    (2): ReLU()
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (4): Conv2d(24, 48, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (5): BatchNorm2d(48, eps=1e-05, momentum=0.1, affine=True, bias=True, track_running_stats=True)
    (6): ReLU()
    (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (8): Conv2d(48, 96, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, bias=True, track_running_stats=True)
    (10): ReLU()
  )
  (pool): AdaptiveAvgPool2d(output_size=(4, 4))
  (dropout): Dropout(p=0.3, inplace=False)
  (classifier): Linear(in_features=1536, out_features=2, bias=True)
)
Trainable parameters: 55634

## 7. Training with validation-only early stopping

In [7]:
def evaluate_loss(model, loader):
    model.eval()
    total_loss = 0.0
    total_rows = 0

    with torch.no_grad():
        for images, labels in loader:
            images = images.to(DEVICE)
            labels = labels.view(-1).long().to(DEVICE)

            logits = model(images)
            loss = criterion(logits, labels)

            total_loss += loss.item() * len(labels)
            total_rows += len(labels)

    return total_loss / total_rows


best_state = None
best_val_loss = float("inf")
patience = 5
epochs_without_improvement = 0
history = []

MAX_EPOCHS = 20

for epoch in range(1, MAX_EPOCHS + 1):
    model.train()

    train_loss_sum = 0.0
    train_rows = 0

    for images, labels in train_loader:
        images = images.to(DEVICE)
        labels = labels.view(-1).long().to(DEVICE)

        optimizer.zero_grad(set_to_none=True)
        logits = model(images)
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()

        train_loss_sum += loss.item() * len(labels)
        train_rows += len(labels)

    train_loss = train_loss_sum / train_rows
    val_loss = evaluate_loss(model, val_loader)

    history.append({
        "epoch": epoch,
        "train_loss": train_loss,
        "val_loss": val_loss,
    })

    print(
        f"epoch={epoch:02d} "
        f"train_loss={train_loss:.4f} "
        f"val_loss={val_loss:.4f}"
    )

    if val_loss < best_val_loss - 1e-4:
        best_val_loss = val_loss
        best_state = {
            key: value.detach().cpu().clone()
            for key, value in model.state_dict().items()
        }
        epochs_without_improvement = 0
    else:
        epochs_without_improvement += 1

    if epochs_without_improvement >= patience:
        print("Early stopping triggered.")
        break

model.load_state_dict(best_state)
model.to(DEVICE)
model.eval()

history_df = pd.DataFrame(history)

history_df.plot(
    x="epoch",
    y=["train_loss", "val_loss"],
    figsize=(8, 4),
    marker="o",
)
plt.title("Real-data training history")
plt.ylabel("Weighted cross-entropy loss")
plt.show()

print("Best validation loss:", round(best_val_loss, 4))
print("Epochs trained:", len(history_df))

epoch=01 train_loss=0.2756 val_loss=2.2881

epoch=02 train_loss=0.1352 val_loss=0.2016

epoch=03 train_loss=0.1150 val_loss=0.1292

epoch=04 train_loss=0.1003 val_loss=0.1559

epoch=05 train_loss=0.0935 val_loss=0.0838

epoch=06 train_loss=0.0900 val_loss=0.0888

epoch=07 train_loss=0.0788 val_loss=0.0822

epoch=08 train_loss=0.0720 val_loss=0.0787

epoch=09 train_loss=0.0717 val_loss=0.1506

epoch=10 train_loss=0.0691 val_loss=0.3157

epoch=11 train_loss=0.0658 val_loss=0.0626

epoch=12 train_loss=0.0689 val_loss=0.1285

epoch=13 train_loss=0.0588 val_loss=0.0733

epoch=14 train_loss=0.0598 val_loss=0.0731

epoch=15 train_loss=0.0556 val_loss=0.1029

epoch=16 train_loss=0.0497 val_loss=0.0798
Early stopping triggered.
Best validation loss: 0.0626
Epochs trained: 16

## 8. Prediction helpers and metric contract

For an imbalanced medical-imaging task, accuracy alone is inadequate. The notebook reports discrimination, class-specific operating characteristics and probability quality.

In [8]:
def collect_logits(model, loader):
    model.eval()
    logits_list = []
    labels_list = []

    with torch.no_grad():
        for images, labels in loader:
            logits = model(images.to(DEVICE)).cpu()
            logits_list.append(logits)
            labels_list.append(labels.view(-1).long())

    return torch.cat(logits_list), torch.cat(labels_list)


def softmax_numpy(logits, temperature=1.0):
    x = np.asarray(logits, dtype=float) / float(temperature)
    x = x - x.max(axis=1, keepdims=True)
    exp_x = np.exp(x)
    return exp_x / exp_x.sum(axis=1, keepdims=True)


def classification_metrics(
    labels,
    probabilities,
    threshold=0.5,
    model_name="model",
):
    labels = np.asarray(labels).astype(int)
    probabilities = np.asarray(probabilities)
    positive_probability = probabilities[:, 1]
    predictions = (positive_probability >= threshold).astype(int)

    tn, fp, fn, tp = confusion_matrix(
        labels,
        predictions,
        labels=[0, 1],
    ).ravel()

    return {
        "model": model_name,
        "threshold": threshold,
        "accuracy": accuracy_score(labels, predictions),
        "balanced_accuracy": balanced_accuracy_score(labels, predictions),
        "precision_pneumonia": precision_score(
            labels, predictions, zero_division=0
        ),
        "sensitivity_pneumonia": recall_score(
            labels, predictions, pos_label=1
        ),
        "specificity_normal": tn / max(tn + fp, 1),
        "f1_pneumonia": f1_score(
            labels, predictions, pos_label=1
        ),
        "roc_auc": roc_auc_score(labels, positive_probability),
        "pr_auc": average_precision_score(labels, positive_probability),
        "mcc": matthews_corrcoef(labels, predictions),
        "nll": log_loss(labels, probabilities),
        "brier": brier_score_loss(labels, positive_probability),
    }


val_logits, val_labels = collect_logits(model, val_loader)
test_logits, test_labels = collect_logits(model, test_loader)

val_logits_np = val_logits.numpy()
val_labels_np = val_labels.numpy()
test_logits_np = test_logits.numpy()
test_labels_np = test_labels.numpy()

test_probs_uncal = torch.softmax(test_logits, dim=1).numpy()

## 9. Validation-only temperature scaling

Temperature is selected by minimizing validation negative log-likelihood. The untouched test set is used only to **measure whether calibration generalizes**. If test calibration worsens, the notebook reports that result rather than hiding it.

In [9]:
def expected_calibration_error(probabilities, labels, bins=10):
    probabilities = np.asarray(probabilities)
    labels = np.asarray(labels)

    confidence = probabilities.max(axis=1)
    prediction = probabilities.argmax(axis=1)

    ece = 0.0
    edges = np.linspace(0, 1, bins + 1)

    for left, right in zip(edges[:-1], edges[1:]):
        mask = (confidence > left) & (confidence <= right)

        if not mask.any():
            continue

        accuracy = (prediction[mask] == labels[mask]).mean()
        avg_confidence = confidence[mask].mean()
        ece += mask.mean() * abs(accuracy - avg_confidence)

    return float(ece)


temperature_grid = np.linspace(0.5, 4.0, 141)

val_nll = [
    log_loss(
        val_labels_np,
        softmax_numpy(val_logits_np, temperature),
    )
    for temperature in temperature_grid
]

best_temperature = float(
    temperature_grid[int(np.argmin(val_nll))]
)

val_probs_cal = softmax_numpy(
    val_logits_np,
    best_temperature,
)

test_probs_cal = softmax_numpy(
    test_logits_np,
    best_temperature,
)

nll_before = log_loss(test_labels_np, test_probs_uncal)
nll_after = log_loss(test_labels_np, test_probs_cal)

ece_before = expected_calibration_error(
    test_probs_uncal,
    test_labels_np,
)
ece_after = expected_calibration_error(
    test_probs_cal,
    test_labels_np,
)

calibration_report = pd.DataFrame([{
    "temperature": best_temperature,
    "test_ECE_before": ece_before,
    "test_ECE_after": ece_after,
    "test_NLL_before": nll_before,
    "test_NLL_after": nll_after,
    "NLL_generalized": nll_after < nll_before,
    "ECE_generalized": ece_after < ece_before,
}])

display(calibration_report.round(4))

,temperature,test_ECE_before,test_ECE_after,test_NLL_before,test_NLL_after,NLL_generalized,ECE_generalized
0,0.925,0.0516,0.0556,0.3508,0.3691,False,False

## 10. Validation-only operating threshold

For an **illustrative triage policy**, validation sensitivity is constrained to at least 95%, then specificity is maximized. This is a modelling exercise, **not a clinically validated threshold**.

In [10]:
def threshold_sweep(y_true, probabilities):
    positive_probability = probabilities[:, 1]
    rows = []

    for threshold in np.linspace(0.05, 0.95, 181):
        prediction = (
            positive_probability >= threshold
        ).astype(int)

        tn, fp, fn, tp = confusion_matrix(
            y_true,
            prediction,
            labels=[0, 1],
        ).ravel()

        sensitivity = tp / max(tp + fn, 1)
        specificity = tn / max(tn + fp, 1)

        rows.append({
            "threshold": threshold,
            "sensitivity": sensitivity,
            "specificity": specificity,
            "balanced_accuracy": (sensitivity + specificity) / 2,
            "f1": f1_score(
                y_true,
                prediction,
                zero_division=0,
            ),
        })

    return pd.DataFrame(rows)


threshold_results = threshold_sweep(
    val_labels_np,
    val_probs_cal,
)

eligible = threshold_results[
    threshold_results["sensitivity"] >= 0.95
]

if len(eligible):
    selected_threshold = eligible.sort_values(
        ["specificity", "balanced_accuracy", "threshold"],
        ascending=[False, False, False],
    ).iloc[0]
else:
    selected_threshold = threshold_results.sort_values(
        ["balanced_accuracy", "f1"],
        ascending=[False, False],
    ).iloc[0]

DECISION_THRESHOLD = float(
    selected_threshold["threshold"]
)

display(selected_threshold.to_frame("selected_value"))
print(
    "Locked illustrative triage threshold:",
    round(DECISION_THRESHOLD, 3),
)

                   selected_value
threshold                0.790000
sensitivity              0.958869
specificity              0.992593
balanced_accuracy        0.975731
f1                       0.977720

Locked illustrative triage threshold: 0.79

## 11. Untouched test evaluation: baseline vs CNN

In [11]:
baseline_metrics = classification_metrics(
    y_test_flat,
    baseline_test_probs,
    threshold=0.5,
    model_name="Balanced pixel logistic baseline",
)

cnn_metrics = classification_metrics(
    test_labels_np,
    test_probs_cal,
    threshold=DECISION_THRESHOLD,
    model_name="PyTorch CNN + validation calibration",
)

comparison = pd.DataFrame([
    baseline_metrics,
    cnn_metrics,
])

display(comparison.round(4))

test_positive_probability = test_probs_cal[:, 1]
test_predictions = (
    test_positive_probability >= DECISION_THRESHOLD
).astype(int)

cm = confusion_matrix(
    test_labels_np,
    test_predictions,
    labels=[0, 1],
)

fig, axes = plt.subplots(1, 3, figsize=(16, 4.8))

# confusion matrix
im = axes[0].imshow(cm, cmap="Blues")
axes[0].set_title("CNN confusion matrix")
axes[0].set_xlabel("Predicted")
axes[0].set_ylabel("Actual")
axes[0].set_xticks([0, 1], CLASS_NAMES)
axes[0].set_yticks([0, 1], CLASS_NAMES)

for i in range(2):
    for j in range(2):
        axes[0].text(
            j, i, int(cm[i, j]),
            ha="center", va="center"
        )

# ROC curves
fpr_base, tpr_base, _ = roc_curve(
    y_test_flat,
    baseline_test_probs[:, 1],
)
fpr_cnn, tpr_cnn, _ = roc_curve(
    test_labels_np,
    test_positive_probability,
)

axes[1].plot(
    fpr_base, tpr_base,
    label=f"Baseline AUC={baseline_metrics['roc_auc']:.3f}",
)
axes[1].plot(
    fpr_cnn, tpr_cnn,
    label=f"CNN AUC={cnn_metrics['roc_auc']:.3f}",
)
axes[1].plot([0, 1], [0, 1], linestyle="--")
axes[1].set_title("ROC curve")
axes[1].set_xlabel("False-positive rate")
axes[1].set_ylabel("True-positive rate")
axes[1].legend()

# Precision-recall curves
precision_base, recall_base, _ = precision_recall_curve(
    y_test_flat,
    baseline_test_probs[:, 1],
)
precision_cnn, recall_cnn, _ = precision_recall_curve(
    test_labels_np,
    test_positive_probability,
)

axes[2].plot(
    recall_base, precision_base,
    label=f"Baseline AP={baseline_metrics['pr_auc']:.3f}",
)
axes[2].plot(
    recall_cnn, precision_cnn,
    label=f"CNN AP={cnn_metrics['pr_auc']:.3f}",
)
axes[2].set_title("Precision-recall curve")
axes[2].set_xlabel("Recall")
axes[2].set_ylabel("Precision")
axes[2].legend()

plt.tight_layout()
plt.show()

,model,threshold,accuracy,balanced_accuracy,precision_pneumonia,sensitivity_pneumonia,specificity_normal,f1_pneumonia,roc_auc,pr_auc,mcc,nll,brier
0,Balanced pixel logistic baseline,0.50,0.8638,0.8261,0.8337,0.9769,0.6752,0.8996,0.9183,0.9170,0.7131,0.5719,0.1138
1,PyTorch CNN + validation calibration,0.79,0.9247,0.9064,0.9074,0.9795,0.8333,0.9420,0.9657,0.9756,0.8399,0.3691,0.0841

## 12. Reliability diagram

This checks whether predicted confidence tracks observed frequency. Calibration quality is a separate problem from discrimination quality.

In [12]:
def reliability_frame(
    labels,
    probabilities,
    bins=10,
):
    frame = pd.DataFrame({
        "label": np.asarray(labels),
        "probability": np.asarray(probabilities)[:, 1],
    })

    frame["bin"] = pd.cut(
        frame["probability"],
        bins=np.linspace(0, 1, bins + 1),
        include_lowest=True,
    )

    return (
        frame.groupby("bin", observed=True)
        .agg(
            mean_probability=("probability", "mean"),
            observed_rate=("label", "mean"),
            count=("label", "size"),
        )
        .dropna()
        .reset_index()
    )


reliability_uncal = reliability_frame(
    test_labels_np,
    test_probs_uncal,
)

reliability_cal = reliability_frame(
    test_labels_np,
    test_probs_cal,
)

plt.figure(figsize=(6, 6))

plt.plot(
    reliability_uncal["mean_probability"],
    reliability_uncal["observed_rate"],
    marker="o",
    label="Before temperature scaling",
)

plt.plot(
    reliability_cal["mean_probability"],
    reliability_cal["observed_rate"],
    marker="o",
    label="After temperature scaling",
)

plt.plot(
    [0, 1],
    [0, 1],
    linestyle="--",
    label="Perfect calibration",
)

plt.xlabel("Predicted pneumonia probability")
plt.ylabel("Observed pneumonia rate")
plt.title("Held-out reliability diagram")
plt.legend()
plt.show()

## 13. Confidence-based human review

A high-stakes system should be allowed to abstain. This policy uses **validation confidence only** to choose a review threshold that preserves at least 75% automatic coverage while maximizing accepted-case accuracy.

In [13]:
val_confidence = val_probs_cal.max(axis=1)
val_prediction = val_probs_cal.argmax(axis=1)

policy_rows = []

for threshold in np.linspace(0.50, 0.98, 97):
    accepted = val_confidence >= threshold
    coverage = accepted.mean()

    selective_accuracy = (
        (
            val_prediction[accepted]
            == val_labels_np[accepted]
        ).mean()
        if accepted.any()
        else np.nan
    )

    policy_rows.append({
        "threshold": threshold,
        "coverage": coverage,
        "selective_accuracy": selective_accuracy,
    })

policy_df = pd.DataFrame(policy_rows)

eligible_review = policy_df[
    policy_df["coverage"] >= 0.75
]

chosen_review = eligible_review.sort_values(
    ["selective_accuracy", "threshold"],
    ascending=[False, False],
).iloc[0]

REVIEW_THRESHOLD = float(
    chosen_review["threshold"]
)

test_confidence = test_probs_cal.max(axis=1)
accepted = test_confidence >= REVIEW_THRESHOLD
errors = test_predictions != test_labels_np

selective_report = pd.DataFrame([{
    "review_threshold": REVIEW_THRESHOLD,
    "automatic_coverage": accepted.mean(),
    "review_rate": (~accepted).mean(),
    "accuracy_on_accepted": (
        (
            test_predictions[accepted]
            == test_labels_np[accepted]
        ).mean()
        if accepted.any()
        else np.nan
    ),
    "test_errors_escalated": (
        ((~accepted) & errors).sum() / errors.sum()
        if errors.sum()
        else 0.0
    ),
}])

display(selective_report.round(4))

,review_threshold,automatic_coverage,review_rate,accuracy_on_accepted,test_errors_escalated
0,0.905,0.8365,0.1635,0.9406,0.3404

## 14. MC-dropout uncertainty

Repeated dropout-enabled forward passes provide a useful **uncertainty heuristic**. The dispersion is not a calibrated clinical confidence interval.

In [14]:
def mc_dropout_probabilities(
    model,
    loader,
    passes=25,
):
    model.train()

    all_images = []
    all_labels = []

    for images, labels in loader:
        all_images.append(images)
        all_labels.append(labels.view(-1))

    images = torch.cat(all_images).to(DEVICE)
    labels = torch.cat(all_labels).numpy()

    draws = []

    with torch.no_grad():
        for _ in range(passes):
            logits = model(images)
            draws.append(
                torch.softmax(
                    logits,
                    dim=1,
                ).cpu().numpy()
            )

    model.eval()

    draws = np.stack(draws, axis=0)

    return (
        labels,
        draws.mean(axis=0),
        draws.std(axis=0),
    )


mc_labels, mc_mean, mc_std = (
    mc_dropout_probabilities(
        model,
        test_loader,
        passes=25,
    )
)

mc_prediction = mc_mean.argmax(axis=1)
uncertainty = mc_std.max(axis=1)
correct = mc_prediction == mc_labels

uncertainty_report = pd.DataFrame({
    "true_label": mc_labels,
    "prediction": mc_prediction,
    "confidence": mc_mean.max(axis=1),
    "mc_uncertainty": uncertainty,
    "correct": correct,
})

display(
    uncertainty_report
    .sort_values(
        "mc_uncertainty",
        ascending=False,
    )
    .head(12)
    .round(4)
)

print(
    "Mean uncertainty — correct:",
    round(
        float(
            uncertainty_report.loc[
                correct,
                "mc_uncertainty",
            ].mean()
        ),
        4,
    ),
)

print(
    "Mean uncertainty — incorrect:",
    round(
        float(
            uncertainty_report.loc[
                ~correct,
                "mc_uncertainty",
            ].mean()
        ),
        4,
    ),
)

     true_label  prediction  confidence  mc_uncertainty  correct
107           0           1      0.5949          0.2316    False
456           0           1      0.5311          0.2046    False
469           0           1      0.6398          0.2024    False
593           0           0      0.5564          0.1978     True
349           0           0      0.5573          0.1973     True
255           0           1      0.6122          0.1897    False
313           0           1      0.5904          0.1843    False
473           0           0      0.6761          0.1813     True
61            0           1      0.6278          0.1804    False
102           1           0      0.6646          0.1780    False
394           0           0      0.6780          0.1756     True
446           0           0      0.5608          0.1745     True

Mean uncertainty — correct: 0.023
Mean uncertainty — incorrect: 0.088

## 15. Grad-CAM on a real test X-ray

Grad-CAM highlights spatial regions that influenced the selected class score. It is an interpretability aid, **not proof that the model is reasoning clinically**.

In [15]:
def gradcam_heatmap(
    model,
    image_tensor,
    target_class=None,
):
    activations = []
    gradients = []

    target_layer = model.features[8]

    def forward_hook(_module, _inputs, output):
        activations.append(output)

    def backward_hook(
        _module,
        _grad_input,
        grad_output,
    ):
        gradients.append(grad_output[0])

    fh = target_layer.register_forward_hook(
        forward_hook
    )
    bh = target_layer.register_full_backward_hook(
        backward_hook
    )

    try:
        model.eval()
        model.zero_grad(set_to_none=True)

        image_tensor = image_tensor.to(DEVICE)
        logits = model(image_tensor)

        if target_class is None:
            target_class = int(
                logits.argmax(dim=1).item()
            )

        logits[0, target_class].backward()

        fmap = activations[-1]
        grad = gradients[-1]

        weights = grad.mean(
            dim=(2, 3),
            keepdim=True,
        )

        cam = torch.relu(
            (weights * fmap).sum(
                dim=1,
                keepdim=True,
            )
        )

        cam = F.interpolate(
            cam,
            size=image_tensor.shape[-2:],
            mode="bilinear",
            align_corners=False,
        )

        cam = cam[0, 0]
        cam = cam - cam.min()
        cam = cam / cam.max().clamp_min(1e-12)

        return cam.detach().cpu().numpy()

    finally:
        fh.remove()
        bh.remove()


example_index = int(
    np.argmax(test_positive_probability)
)

example_image, example_label = (
    test_dataset[example_index]
)

example_batch = example_image.unsqueeze(0)

heatmap = gradcam_heatmap(
    model,
    example_batch,
    target_class=1,
)

fig, axes = plt.subplots(
    1,
    3,
    figsize=(11, 3.6),
)

axes[0].imshow(
    example_image.squeeze(0),
    cmap="gray",
)
axes[0].set_title("Real test X-ray")
axes[0].axis("off")

axes[1].imshow(
    heatmap,
    cmap="inferno",
)
axes[1].set_title("Grad-CAM")
axes[1].axis("off")

axes[2].imshow(
    example_image.squeeze(0),
    cmap="gray",
)
axes[2].imshow(
    heatmap,
    cmap="inferno",
    alpha=0.45,
)
axes[2].set_title("Overlay")
axes[2].axis("off")

plt.tight_layout()
plt.show()

true_index = int(
    np.asarray(
        example_label
    ).reshape(-1)[0]
)

pred_index = int(
    test_predictions[example_index]
)

print(
    "True class:",
    CLASS_NAMES[true_index],
)
print(
    "Predicted class:",
    CLASS_NAMES[pred_index],
)
print(
    "Pneumonia probability:",
    round(
        float(
            test_positive_probability[
                example_index
            ]
        ),
        4,
    ),
)

True class: pneumonia
Predicted class: pneumonia
Pneumonia probability: 1.0

## 16. Qualitative error analysis

Looking at mistakes is more useful than reporting one headline score. The gallery below shows high-confidence errors from the untouched test set.

In [16]:
error_indices = np.where(
    test_predictions != test_labels_np
)[0]

if len(error_indices):
    error_confidence = np.abs(
        test_positive_probability[
            error_indices
        ] - 0.5
    )

    selected_errors = error_indices[
        np.argsort(
            error_confidence
        )[::-1][:8]
    ]

    fig, axes = plt.subplots(
        2,
        4,
        figsize=(11, 6),
    )

    for ax, idx in zip(
        axes.ravel(),
        selected_errors,
    ):
        image, label = test_dataset[
            int(idx)
        ]

        true_label = int(
            np.asarray(label).reshape(-1)[0]
        )

        predicted_label = int(
            test_predictions[idx]
        )

        ax.imshow(
            image.squeeze(0),
            cmap="gray",
        )

        ax.set_title(
            f"true={CLASS_NAMES[true_label]}\n"
            f"pred={CLASS_NAMES[predicted_label]} "
            f"p={test_positive_probability[idx]:.2f}",
            fontsize=9,
        )

        ax.axis("off")

    plt.suptitle(
        "High-confidence errors on real held-out X-rays"
    )
    plt.tight_layout()
    plt.show()
else:
    print("No test errors to display.")

## 17. Corruption stress test

This is an engineering robustness test, not a clinical distribution-shift study. The goal is to demonstrate that strong clean-set performance does not guarantee resilience to image-quality degradation.

In [17]:
all_test_images = []
all_test_labels = []

for images, labels in test_loader:
    all_test_images.append(images)
    all_test_labels.append(
        labels.view(-1)
    )

clean_images = torch.cat(
    all_test_images
)
clean_labels = torch.cat(
    all_test_labels
)

generator = torch.Generator().manual_seed(
    SEED + 1
)

noise = torch.randn(
    clean_images.shape,
    generator=generator,
) * 0.12

corrupted_images = torch.clamp(
    clean_images * 0.85
    + 0.075
    + noise,
    0,
    1,
)

corrupted_loader = DataLoader(
    TensorDataset(
        corrupted_images,
        clean_labels,
    ),
    batch_size=256,
    shuffle=False,
)

corrupted_logits, corrupted_labels = (
    collect_logits(
        model,
        corrupted_loader,
    )
)

corrupted_probs = softmax_numpy(
    corrupted_logits.numpy(),
    best_temperature,
)

corrupted_metrics = classification_metrics(
    corrupted_labels.numpy(),
    corrupted_probs,
    threshold=DECISION_THRESHOLD,
    model_name="CNN under noise stress",
)

robustness = pd.DataFrame([
    {
        "condition": "clean real test",
        **cnn_metrics,
    },
    {
        "condition": "noise stress test",
        **corrupted_metrics,
    },
])

display(
    robustness[
        [
            "condition",
            "balanced_accuracy",
            "sensitivity_pneumonia",
            "specificity_normal",
            "f1_pneumonia",
            "roc_auc",
            "pr_auc",
        ]
    ].round(4)
)

robustness.plot.bar(
    x="condition",
    y=[
        "balanced_accuracy",
        "roc_auc",
        "pr_auc",
    ],
    figsize=(8, 4),
    rot=0,
)

plt.ylim(0, 1)
plt.title(
    "Performance under image corruption"
)
plt.show()

,condition,balanced_accuracy,sensitivity_pneumonia,specificity_normal,f1_pneumonia,roc_auc,pr_auc
0,clean real test,0.9064,0.9795,0.8333,0.9420,0.9657,0.9756
1,noise stress test,0.8188,0.8897,0.7479,0.8719,0.9051,0.9270

## 18. Deployment profile and integrity checks

In [18]:
model_cpu = PneumoniaCNN(
    dropout=0.30
).cpu()

model_cpu.load_state_dict({
    key: value.detach().cpu()
    for key, value
    in model.state_dict().items()
})

model_cpu.eval()

sample = next(
    iter(test_loader)
)[0][:1].cpu()

with torch.no_grad():
    for _ in range(10):
        _ = model_cpu(sample)

    repeats = 200
    start = time.perf_counter()

    for _ in range(repeats):
        _ = model_cpu(sample)

    latency_ms = (
        time.perf_counter() - start
    ) / repeats * 1000

buffer = io.BytesIO()
torch.save(
    model_cpu.state_dict(),
    buffer,
)

deployment_profile = pd.DataFrame([{
    "trainable_parameters": sum(
        p.numel()
        for p in model_cpu.parameters()
        if p.requires_grad
    ),
    "state_dict_MB": (
        buffer.tell()
        / (1024 ** 2)
    ),
    "batch1_cpu_latency_ms": latency_ms,
}])

display(
    deployment_profile.round(4)
)

assert len(train_dataset) == 4708
assert len(val_dataset) == 524
assert len(test_dataset) == 624
assert set(np.unique(y_train_np)) == {0, 1}
assert test_logits.shape == (624, 2)

assert np.isfinite(
    test_probs_cal
).all()

assert np.allclose(
    test_probs_cal.sum(axis=1),
    1.0,
    atol=1e-6,
)

assert (
    0
    <= cnn_metrics["roc_auc"]
    <= 1
)

assert (
    0
    <= cnn_metrics["pr_auc"]
    <= 1
)

assert heatmap.shape == (
    IMAGE_SIZE,
    IMAGE_SIZE,
)

assert np.isfinite(
    heatmap
).all()

assert (
    0
    <= heatmap.min()
    <= heatmap.max()
    <= 1.0 + 1e-6
)

print(
    "All real-data medical-AI integrity checks passed."
)
print(
    "Primary dataset: PneumoniaMNIST "
    "(real chest X-rays)"
)
print(
    "Clinical use: prohibited — "
    "research/education only"
)

   trainable_parameters  state_dict_MB  batch1_cpu_latency_ms
0                 55634         0.2207                 1.1029

All real-data medical-AI integrity checks passed.
Primary dataset: PneumoniaMNIST (real chest X-rays)
Clinical use: prohibited — research/education only

## 19. Interview summary and limitations

> **I built a real-data PyTorch chest-X-ray classification study using the official PneumoniaMNIST benchmark. I compared a balanced pixel-level logistic baseline with a CNN, used validation-only early stopping, temperature scaling and an illustrative sensitivity-constrained operating threshold, evaluated sensitivity/specificity, PR-AUC, ROC-AUC, F1, MCC, Brier and calibration, added selective human review and MC-dropout uncertainty, generated Grad-CAM explanations, inspected high-confidence errors, stress-tested image corruption and profiled model size/CPU latency.**

### What I would say explicitly in an interview
- This is a **research/education benchmark**, not a medical device.
- MedMNIST images are standardized and small; strong benchmark performance does not imply clinical generalization.
- Calibration is evaluated honestly: if it worsens on the held-out test set, that is evidence the calibration step did not generalize cleanly.
- The 95% validation sensitivity constraint is an **illustrative modelling choice**, not a clinical requirement.
- The dataset lacks the metadata needed for a meaningful demographic subgroup audit.
- A clinical study would require patient-level provenance, external-site validation, prospective evaluation, clinically defined thresholds, governance and human oversight.

### Strong next extension
Move from a lightweight benchmark to a larger real chest-X-ray dataset with patient-level splits, external validation and out-of-distribution evaluation, while retaining the same leakage, calibration, abstention and explainability discipline.